version: '3.7'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/julo-test
    ports: 
      - 5000:5000 # API server
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:15
    container_name: julo-test-pg
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: julotest
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
volumes:
  pg_data: